version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_back
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tutorias
      MYSQL_USER: tutor_user
      MYSQL_PASSWORD: tutorpass
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tutorias
      SPRING_DATASOURCE_USERNAME: tutor_user
      SPRING_DATASOURCE_PASSWORD: tutorpass

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data: